Updated EventsManager and EventInfo with some new test cases
bravetheheat/csc207_2020_group_074_phase1 pull request #35
Opened 2020-11-10 21:12 UTC by oliphant0803

Added test cases for all events usecase
Fixed some bug in eventinfomanager after testing
Added eventFactory and eventBuilder

2020-11-10 21:15 UTC, oliphant0803 commented
I am not sure if I implemented builder and factory correctly, although I think the code function fine and can interact with controllers now, I would like to get some suggestions on how to make these design patterns more efficient to be used in controller.

2020-11-11 00:41 UTC, bravetheheat requested changes

2020-11-11 00:41 UTC, bravetheheat commented on src/main/usecases/EventBuilder.java
> +        return this;
I don't think you need to return this. I think it should be void, but it's not that important

2020-11-11 00:41 UTC, bravetheheat commented on src/main/usecases/EventBuilder.java
> +    }
Love the builder pattern. Great job!

2020-11-11 00:41 UTC, bravetheheat commented on src/main/usecases/EventFactory.java
> +    private final String title;
I don't think this factory setup is useful. This is just adding additional complexity and doesn't make it simpler to create an event

e.g. to use this, you would do EventFactory(...event variables), which isn't simpler than Event(...event variables).

2020-11-11 00:41 UTC, bravetheheat commented on src/main/usecases/EventInfoManager.java
> +                throw new IllegalArgumentException("Time conflict for speaker " + e.getSpeakerID() +
okay, make sure you communicate with everyone that uses this class that this exception should be handled. We don't want an exception to crash the program.

2020-11-11 00:41 UTC, bravetheheat commented on src/main/usecases/EventInfoManager.java
> +                throw new IllegalArgumentException("Time conflict for speaker " + e.getSpeakerID() +
Also make sure you create tests for this.

2020-11-11 00:41 UTC, bravetheheat commented on src/main/usecases/EventsManager.java
> +    private LinkedHashMap<UUID,Event> schedule = new LinkedHashMap<>();
Keep it as interface Map.

2020-11-11 00:41 UTC, bravetheheat commented on test/EventsInfoTest.java
> +        room1 = UUID.randomUUID();
I get why you did it this way, but I recommend against this.

2020-11-11 00:41 UTC, bravetheheat commented
@kaka0905 @AveritasR0679 @YvetteXie @yitaoli97 @Hiraethwly what do you guys think of the Factory pattern?

2020-11-11 00:43 UTC, oliphant0803 commented on src/main/usecases/EventFactory.java
> +    private final String title;
I agree with that, but it will be useful later to distinguish between different types of events. So I wonder do we keep it this one, or remove it. I personally think we don't need it.

2020-11-11 00:47 UTC, oliphant0803 commented on src/main/usecases/EventsManager.java
> +    private LinkedHashMap<UUID,Event> schedule = new LinkedHashMap<>();
If we make it a map, then toString method will print in random order, I am afraid that we do not want to handle with random order when it prints out

2020-11-11 01:00 UTC, kaka0905 reviewed
I think that using a factory method is a good idea, but since for phase 1, we only have one type of event, we do not need to cover this so far. However, I think we can save this for Phase 2.

2020-11-11 01:11 UTC, bravetheheat commented on src/main/usecases/EventsManager.java
> +    private LinkedHashMap<UUID,Event> schedule = new LinkedHashMap<>();
Because the implementation is a LinkedHashMap, it won't print in random order. It's an interface, so the definition of the method will be determined by the LinkedHashMap

2020-11-11 01:17 UTC, oliphant0803 commented on src/main/usecases/EventsManager.java
> +    private LinkedHashMap<UUID,Event> schedule = new LinkedHashMap<>();
I get it, I will fix it.

2020-11-11 02:21 UTC, oliphant0803 reviewed
These are the new changes

2020-11-11 02:22 UTC, oliphant0803 commented on src/main/usecases/EventFactory.java
> +    public EventFactory(String title, LocalDateTime time, UUID roomID, UUID speakerID){
I unused this class in the recent commit

2020-11-11 02:28 UTC, oliphant0803 reviewed
Please check the most recent commit

2020-11-11 05:13 UTC, vesteny77 approved these changes

2020-11-11 15:01 UTC, bravetheheat approved these changes

2020-11-11 15:01 UTC, merged